--- #YAML:1.0
name:                Pod-Perldoc-ToToc
version:             1.08
abstract:            Turn one or more Pod files into a table of contents
license:             perl
generated_by:        ExtUtils::MakeMaker version 6.36
distribution_type:   module
requires:     
    Pod::Perldoc:                  0
    Pod::Simple:                   0
    Test::More:                    0
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.3.html
    version: 1.3
author:
    - brian d foy <bdfoy@cpan.org>
