---
abstract: 'Turn one or more Pod files into a table of contents'
author:
  - 'brian d foy <bdfoy@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.62, CPAN::Meta::Converter version 2.112150'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Pod-Perldoc-ToToc
no_index:
  directory:
    - t
    - inc
requires:
  ExtUtils::MakeMaker: 6.46
  Pod::Perldoc: 0
  Pod::Simple: 0
  Test::More: 0.95
  parent: 0
resources:
  repository: https://github.com/briandfoy/pod-perldoc-totoc
version: 1.11
